version: "3"
services:
  frontend:
    build:
      context: ./path/to/angular/app
      dockerfile: Dockerfile
    ports:
      - 4200:4200

  backend:
    build:
      context: ./path/to/dotnet/app
      dockerfile: Dockerfile
    ports:
      - 5000:5000
