version: "3.9"
services:
  frontend:
    build:
      context: C:\Users\fares\MdWeb\frontend
      dockerfile: Dockerfile-angular
    ports:
      - 80:80

  backend:
    build:
      context: C:\Users\fares\MdWeb\backend
      dockerfile: Dockerfile-dotnet
    ports:
      - 5000:5000
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - 27017:27017
